Доработки filmorate для ТЗ10
MorgunovAndreyV/java-filmorate pull request #7
Opened 2023-11-19 17:54 UTC by MorgunovAndreyV

2023-11-20 09:21 UTC, avlin87 requested changes
Привет, Андрей,
Работа выглядит хорошо.
Смотри, пожалуйста, комментарии, что можно улучшить.

2023-11-20 09:21 UTC, avlin87 commented on src/main/java/ru/yandex/practicum/filmorate/controller/ErrorHandler.java
> +        return new ExceptionResponse(
Добавь, пожалуйста, логирование в методы, перед возвратом ошибки.

2023-11-20 09:21 UTC, avlin87 commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private final FilmStorage filmStorage;
Перенеси, пожалуйста, вызовы FilmStorage класса в FilmService.

2023-11-20 09:21 UTC, avlin87 commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    private final UserStorage userStorage;
Перенеси, пожалуйста, вызовы UserStorage в UserService класс.

2023-11-20 11:58 UTC, MorgunovAndreyV commented on src/main/java/ru/yandex/practicum/filmorate/controller/ErrorHandler.java
> +        return new ExceptionResponse(
Привет! Добавил логирование в методы

2023-11-20 11:58 UTC, MorgunovAndreyV commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private final FilmStorage filmStorage;
Готово

2023-11-20 11:59 UTC, MorgunovAndreyV commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    private final UserStorage userStorage;
Готово

2023-11-21 01:41 UTC, avlin87 approved these changes
Хорошо, работу принимаю.

2023-12-12 20:31 UTC, merged