feat. ТЗ-11. Добавление БД. Коммит для сохранения всех изменений
MorgunovAndreyV/java-filmorate pull request #8
Opened 2023-12-17 02:21 UTC by MorgunovAndreyV

2023-12-17 08:35 UTC, avlin87 requested changes
Привет, Андрей,
Хорошая работа, смотри, пожалуйста, комментарии ниже.

2023-12-17 08:35 UTC, avlin87 commented on src/main/java/ru/yandex/practicum/filmorate/controller/GenreController.java
> +    public GenreController(FilmService filmService) {
`*можно лучше*`
Конструктор можно заменить аннотацией `@RequiredArgsConstructor` - он сгенерирует конструктор для final полей, которые еще не проинициализированы.

Так же и в остальных классах.

2023-12-17 08:35 UTC, avlin87 commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
>      private final Comparator<Film> filmComparatorByLikes = new FilmComparatorByLikes();
При работе с Spring мы стараемся избавиться от необходимости ручной инициализации объектов.
Предлагаю:
1. вынести класс `FilmComparatorByLikes` в отдельный файл, можешь для компараторов создать отдельный пакет.
2. На классе `FilmComparatorByLikes` поставить аннотацию `@Component`.
3. И так же ожидать, что переменная filmComparatorByLikes будет инициализирована в конструкторе.


Так же и с `UserComparatorById` в следующем классе.

2023-12-17 08:35 UTC, avlin87 commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDbStorage.java
> +        String sqlQuery = "SELECT * from GENRES";
Лучше не использовать `SELECT *`
а указывать конкретные имена колонок.
1. Наша модель может не совпасть с таблицей если в ней добавят колонки или поменяют их местами.
2. Производительность запросов с конкретными именами выше.
3. Так же имена колонок повысят читаемость кода.

В других местах так же.

2023-12-17 12:55 UTC, MorgunovAndreyV commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
>      private final Comparator<Film> filmComparatorByLikes = new FilmComparatorByLikes();
Перенес компараторы в отдельные классы

2023-12-17 12:55 UTC, MorgunovAndreyV commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDbStorage.java
> +        String sqlQuery = "SELECT * from GENRES";
Пофиксил - явно указал требуемые колонки

2023-12-18 02:00 UTC, avlin87 approved these changes
Работу принимаю.

2023-12-25 11:02 UTC, merged